node_name: '${env.NODE_NAME}'

consul:
  address: '${env.CONSUL_HTTP_ADDR}'
  datacenter: ''
  token: '${env.CONSUL_HTTP_TOKEN}'
  prefix: 'replctl/v1'
  order_history_keep: 10

tasks:
  mongo_controller:
    enabled: true
    instance_number: 1                 # set 1 on one node, 2 on another (standby), etc.
    controller_id: ''                   # optional; if empty -> NODE_NAME + #instance_number
    lock_key: 'locks/mongo-controller'
    state_key: 'state/mongo-controller'
    candidates_prefix: 'candidates/mongo'
    health_prefix: 'health/mongo'
    spec_key: 'spec/mongo'
    replica_set_id: 'rs0'             # desired replica set name (_id in local.system.replset)
    election_interval: '10s'
    initial_settle_duration: '3s'   # debounce window before choosing initial 3 members
    allow_degraded_single_member: false

  mongo_agent:
    enabled: true
    agent_id: '${env.NODE_NAME}'
    worker_id: '${env.NODE_NAME}'
    member_id: ${env.CONSOLE_ID}    # replica set member _id (unique per node)
    orders_key: 'orders/mongo/${env.NODE_NAME}'
    ack_key: 'acks/mongo/${env.NODE_NAME}'
    report_key: 'candidates/mongo/${env.NODE_NAME}'
    health_key: 'health/mongo/${env.NODE_NAME}'
    mongod_path: '${env.MONGO_TOOLS}/mongod.exe'
    dbpath: '${env.MONGO_DB_PATH}'
    bind_ip: '${env.CSB_IP}'
    bind_addr: '${env.MONGO_ADDR}'
    temp_port: 27017                # local temporary port for offline probe
    admin_user: 'admin'
    admin_pass: '123'
    port: 27017
    replset_name: 'rs0'
    log_path: '${env.MONGO_LOG_PATH}'
    service:
      enabled: true
      address: '${env.CSB_IP}'
      ttl: '15s'
      tags: ['mongo']

  kafka_controller:
    enabled: true
    instance_number: 1
    controller_id: ''
    lock_key: 'locks/kafka-controller'
    state_key: 'state/kafka-controller'
    candidates_prefix: 'candidates/kafka'
    health_prefix: 'health/kafka'
    spec_key: 'spec/kafka'
    election_interval: '10s'
    initial_settle_duration: '5s'   # debounce window before choosing initial 3 members
    allow_degraded_single_member: false

  kafka_agent:
    enabled: true
    agent_id: '${env.NODE_NAME}'
    worker_id: '${env.NODE_NAME}'
    report_key: 'candidates/kafka/${env.NODE_NAME}'
    orders_key: 'orders/kafka/${env.NODE_NAME}'
    ack_key: 'acks/kafka/${env.NODE_NAME}'
    health_key: 'health/kafka/${env.NODE_NAME}'
    kafka_bin_dir: '${env.KAFKA_TOOLS}'
    work_dir: '${env.CMS_ROOT}'
    log_dir: '${env.KAFKA_DATA_DIR}'
    meta_log_dir: '${env.KAFKA_META_DIR}'
    broker_addr: '${env.CSB_IP}:9092'
    controller_addr: '${env.CSB_IP}:9093'
    cluster_id: '${env.KAFKA_CLUSTER_ID}'
    node_id: '${env.CONSOLE_ID}'
    storage_id: '${env.KAFKA_STORAGE_ID}'
    # meta_dirs:
    service:
      enabled: true
      address: '${env.CSB_IP}'
      ttl: '15s'
      tags: ['kafka','kraf','combined']


  services_controller:
    enabled: true
    instance_number: 1
    controller_id: ''
    lock_key: 'locks/services-controller'
    state_key: 'state/services-controller'
    kafka_candidates_prefix: 'candidates/kafka'
    mongo_candidates_prefix: 'candidates/mongo'
    wait_for: ['mongo','kafka']
    min_passing: 3
    reconcile_interval: '10s'
    services:
      - name: 'SUP-RM-SERVER'
        instances: 2
        tags: ['dpagent','exgw']
        ttl: '15s'
        depends_on: []
        depends_min_passing: 0
        start:
          cmd: 'java.exe'
          args: [
            '-DAGENT_ID=SUP-RM-SERVER',
            '-DAGENT_CLASS=tr.com.havelsan.agosta.c2is.sup.rm.agent.agent.RMDPAgent',
            '-DCLUSTER_ID=${env.CONSOLE_ID}',
            '-DDEFAULT_SIM_MODE=OFF',
            'tr.com.havelsan.cmscore.mw.dpagent.DPAgent'
          ]
          work_dir: '${env.CMS_ROOT}'

      - name: 'BITE'
        instances: 2
        tags: ['dpagent','exgw']
        ttl: '15s'
        depends_on: []
        depends_min_passing: 0
        start:
          cmd: 'java.exe'
          args: [
            '-DAGENT_ID=BITE',
            '-DAGENT_CLASS=tr.com.havelsan.cmscore.mw.bite.agent.BITEDPAgent',
            '-DCLUSTER_ID=${env.CONSOLE_ID}',
            '-DDEFAULT_SIM_MODE=OFF',
            'tr.com.havelsan.cmscore.mw.dpagent.DPAgent'
          ]
          work_dir: '${env.CMS_ROOT}'

      # - name: 'SUP'
      #   instances: 2
      #   tags: ['dpagent','exgw']
      #   ttl: '15s'
      #   start:
      #     cmd: 'java.exe'
      #     args: [
      #       '-DAGENT_ID=SUP',
      #       '-DAGENT_CLASS=tr.com.havelsan.agosta.c2is.sup.dp.agent.smgdpagent.AgentCommanderDPAgent',
      #       '-DCLUSTER_ID=${env.CONSOLE_ID}',
      #       '-DDEFAULT_SIM_MODE=OFF',
      #       'tr.com.havelsan.cmscore.mw.dpagent.DPAgent'
      #     ]
      #     work_dir: '${env.CMS_ROOT}'

      - name: 'AWIE'
        instances: 2
        tags: ['dpagent','exgw']
        ttl: '15s'
        depends_on: []
        depends_min_passing: 0
        start:
          cmd: 'java.exe'
          args: [
            '-DAGENT_ID=AWIE',
            '-DAGENT_CLASS=tr.com.havelsan.cmscore.mw.awie.agent.AWIEDPAgent',
            '-DCLUSTER_ID=${env.CONSOLE_ID}',
            '-DDEFAULT_SIM_MODE=OFF',
            'tr.com.havelsan.cmscore.mw.dpagent.DPAgent'
          ]
          work_dir: '${env.CMS_ROOT}'

      - name: 'NewAWIE'
        instances: 2
        tags: ['dpagent','exgw']
        ttl: '15s'
        depends_on: []
        depends_min_passing: 0
        start:
          cmd: 'java.exe'
          args: [
            '-DAGENT_ID=NewAWIE',
            '-DAGENT_CLASS=tr.com.havelsan.cmscore.mw.awie.newagent.NewAwieDPAgent',
            '-DCLUSTER_ID=${env.CONSOLE_ID}',
            '-DDEFAULT_SIM_MODE=OFF',
            'tr.com.havelsan.cmscore.mw.dpagent.DPAgent'
          ]
          work_dir: '${env.CMS_ROOT}'

      - name: 'DRS'
        instances: 2
        tags: ['dpagent','exgw']
        ttl: '15s'
        depends_on: []
        depends_min_passing: 0
        start:
          cmd: 'java.exe'
          args: [
            '-DAGENT_ID=DRS',
            '-DAGENT_CLASS=tr.com.havelsan.agosta.c2is.drs.agent.DrsDPAgent',
            '-DCLUSTER_ID=${env.CONSOLE_ID}',
            '-DDEFAULT_SIM_MODE=OFF',
            'tr.com.havelsan.cmscore.mw.dpagent.DPAgent'
          ]
          work_dir: '${env.CMS_ROOT}'

      - name: 'NAV'
        instances: 2
        tags: ['dpagent','exgw']
        ttl: '15s'
        depends_on: []
        depends_min_passing: 0
        start:
          cmd: 'java.exe'
          args: [
            '-DAGENT_ID=NAV',
            '-DAGENT_CLASS=tr.com.havelsan.agosta.c2is.nav.dp.agent.NavDpAgent',
            '-DCLUSTER_ID=${env.CONSOLE_ID}',
            '-DDEFAULT_SIM_MODE=OFF',
            'tr.com.havelsan.cmscore.mw.dpagent.DPAgent'
          ]
          work_dir: '${env.CMS_ROOT}'

      - name: 'EXGW-SDDS-NAV'
        instances: 2
        tags: ['dpagent','exgw']
        ttl: '15s'
        depends_on: []
        depends_min_passing: 0
        start:
          cmd: 'java.exe'
          args: [
            '-DAGENT_ID=EXGW-SDDS-NAV',
            '-DAGENT_CLASS=tr.com.havelsan.agosta.c2is.exgw.nav.agent.ExgwNavDPAgent',
            '-DCLUSTER_ID=${env.CONSOLE_ID}',
            '-DDEFAULT_SIM_MODE=OFF',
            'tr.com.havelsan.cmscore.mw.dpagent.DPAgent'
          ]
          work_dir: '${env.CMS_ROOT}'

      - name: 'EXGW-SDDS-BITE'
        instances: 2
        tags: ['dpagent','exgw']
        ttl: '15s'
        depends_on: []
        depends_min_passing: 0
        start:
          cmd: 'java.exe'
          args: [
            '-DAGENT_ID=EXGW-SDDS-BITE',
            '-DAGENT_CLASS=tr.com.havelsan.agosta.c2is.exgw.sdds.bite.agent.ExgwSddsBiteDPAgent',
            '-DCLUSTER_ID=${env.CONSOLE_ID}',
            '-DDEFAULT_SIM_MODE=OFF',
            'tr.com.havelsan.cmscore.mw.dpagent.DPAgent'
          ]
          work_dir: '${env.CMS_ROOT}'

      - name: 'TM'
        instances: 2
        tags: ['dpagent','exgw']
        ttl: '15s'
        depends_on: []
        depends_min_passing: 0
        start:
          cmd: 'java.exe'
          args: [
            '-DAGENT_ID=TM',
            '-DAGENT_CLASS=tr.com.havelsan.agosta.c2is.tacsit.tm.agent.TacsitTmDpAgent1',
            '-DCLUSTER_ID=${env.CONSOLE_ID}',
            '-DDEFAULT_SIM_MODE=OFF',
            'tr.com.havelsan.cmscore.mw.dpagent.DPAgent'
          ]
          work_dir: '${env.CMS_ROOT}'

      # - name: 'SONARTM'
      #   instances: 3
      #   tags: ['dpagent','exgw']
      #   ttl: '15s'
      #   start:
      #     cmd: 'java.exe'
      #     args: [
      #       '-DAGENT_ID=SONARTM',
      #       '-DAGENT_CLASS=tr.com.havelsan.agosta.c2is.sonar.tm.agent.SonarTmDpAgent',
      #       '-DCLUSTER_ID=${env.CONSOLE_ID}',
      #       '-DDEFAULT_SIM_MODE=OFF',
      #       'tr.com.havelsan.cmscore.mw.dpagent.DPAgent'
      #     ]
      #     work_dir: '${env.CMS_ROOT}'

      - name: 'TACSIT'
        instances: 2
        tags: ['dpagent','exgw']
        ttl: '15s'
        depends_on: []
        depends_min_passing: 0
        start:
          cmd: 'java.exe'
          args: [
            '-DAGENT_ID=TACSIT',
            '-DAGENT_CLASS=tr.com.havelsan.agosta.c2is.tacsit.agent.TACSITDPAgent',
            '-DCLUSTER_ID=${env.CONSOLE_ID}',
            '-DDEFAULT_SIM_MODE=OFF',
            'tr.com.havelsan.cmscore.mw.dpagent.DPAgent'
          ]
          work_dir: '${env.CMS_ROOT}'

      - name: 'TGD'
        instances: 2
        tags: ['dpagent','exgw']
        ttl: '15s'
        depends_on: []
        depends_min_passing: 0
        start:
          cmd: 'java.exe'
          args: [
            '-DAGENT_ID=TGD',
            '-DAGENT_CLASS=tr.com.havelsan.agosta.c2is.tgd.agent.TgdDpAgent',
            '-DCLUSTER_ID=${env.CONSOLE_ID}',
            '-DDEFAULT_SIM_MODE=OFF',
            'tr.com.havelsan.cmscore.mw.dpagent.DPAgent'
          ]
          work_dir: '${env.CMS_ROOT}'

      - name: 'TMA'
        instances: 2
        tags: ['dpagent','exgw']
        ttl: '15s'
        depends_on: []
        depends_min_passing: 0
        start:
          cmd: 'java.exe'
          args: [
            '-DAGENT_ID=TMA',
            '-DAGENT_CLASS=tr.com.havelsan.agosta.c2is.tma.agent.TmaDpAgent',
            '-DCLUSTER_ID=${env.CONSOLE_ID}',
            '-DDEFAULT_SIM_MODE=OFF',
            'tr.com.havelsan.cmscore.mw.dpagent.DPAgent'
          ]
          work_dir: '${env.CMS_ROOT}'

      # - name: 'ISUS'
      #   instances: 2
      #   tags: ['dpagent','exgw']
      #   ttl: '15s'
      #   start:
      #     cmd: 'java.exe'
      #     args: [
      #       '-DAGENT_ID=ISUS',
      #       '-DAGENT_CLASS=tr.com.havelsan.agosta.c2is.tma.agent.IsusIntegrationDpAgent',
      #       '-DCLUSTER_ID=${env.CONSOLE_ID}',
      #       '-DDEFAULT_SIM_MODE=OFF',
      #       'tr.com.havelsan.cmscore.mw.dpagent.DPAgent'
      #     ]
      #     work_dir: '${env.CMS_ROOT}'

      - name: 'EXGW-SONAR-TRACK'
        instances: 2
        tags: ['dpagent','exgw']
        ttl: '15s'
        depends_on: []
        depends_min_passing: 0
        start:
          cmd: 'java.exe'
          args: [
            '-DAGENT_ID=EXGW-SONAR-TRACK',
            '-DAGENT_CLASS=tr.com.havelsan.agosta.c2is.exgw.sonar.agent.ExgwSonarDpAgent',
            '-DCLUSTER_ID=${env.CONSOLE_ID}',
            '-DDEFAULT_SIM_MODE=OFF',
            'tr.com.havelsan.cmscore.mw.dpagent.DPAgent'
          ]
          work_dir: '${env.CMS_ROOT}'

      - name: 'EXGW-SONAR-BITE'
        instances: 2
        tags: ['dpagent','exgw']
        ttl: '15s'
        depends_on: []
        depends_min_passing: 0
        start:
          cmd: 'java.exe'
          args: [
            '-DAGENT_ID=EXGW-SONAR-BITE',
            '-DAGENT_CLASS=tr.com.havelsan.agosta.c2is.exgw.bite.agent.ExgwBiteDpAgent',
            '-DCLUSTER_ID=${env.CONSOLE_ID}',
            '-DDEFAULT_SIM_MODE=OFF',
            'tr.com.havelsan.cmscore.mw.dpagent.DPAgent'
          ]
          work_dir: '${env.CMS_ROOT}'

      - name: 'EXGW-RADAR'
        instances: 2
        tags: ['dpagent','exgw']
        ttl: '15s'
        depends_on: []
        depends_min_passing: 0
        start:
          cmd: 'java.exe'
          args: [
            '-DAGENT_ID=EXGW-RADAR',
            '-DAGENT_CLASS=tr.com.havelsan.agosta.c2is.exgw.radar.aselsan.agent.ExgwRadarAselsanDPAgent',
            '-DCLUSTER_ID=${env.CONSOLE_ID}',
            '-DDEFAULT_SIM_MODE=OFF',
            'tr.com.havelsan.cmscore.mw.dpagent.DPAgent'
          ]
          work_dir: '${env.CMS_ROOT}'

      - name: 'EXGW-ESM'
        instances: 2
        tags: ['dpagent','exgw']
        ttl: '15s'
        depends_on: []
        depends_min_passing: 0
        start:
          cmd: 'java.exe'
          args: [
            '-DAGENT_ID=EXGW-ESM',
            '-DAGENT_CLASS=tr.com.havelsan.agosta.c2is.exgw.esm.agent.ExgwESMDPAgent',
            '-DCLUSTER_ID=${env.CONSOLE_ID}',
            '-DDEFAULT_SIM_MODE=OFF',
            'tr.com.havelsan.cmscore.mw.dpagent.DPAgent'
          ]
          work_dir: '${env.CMS_ROOT}'

      - name: 'EXGW-VRU'
        instances: 2
        tags: ['dpagent','exgw']
        ttl: '15s'
        depends_on: []
        depends_min_passing: 0
        start:
          cmd: 'java.exe'
          args: [
            '-DAGENT_ID=EXGW-VRU',
            '-DAGENT_CLASS=tr.com.havelsan.agosta.c2is.exgw.vruinternal.agent.ExgwVRUInternalDPAgent',
            '-DCLUSTER_ID=${env.CONSOLE_ID}',
            '-DDEFAULT_SIM_MODE=OFF',
            'tr.com.havelsan.cmscore.mw.dpagent.DPAgent'
          ]
          work_dir: '${env.CMS_ROOT}'

      - name: 'EXGW-VDU'
        instances: 2
        tags: ['dpagent','exgw']
        ttl: '15s'
        depends_on: []
        depends_min_passing: 0
        start:
          cmd: 'java.exe'
          args: [
            '-DAGENT_ID=EXGW-VDU',
            '-DAGENT_CLASS=tr.com.havelsan.agosta.c2is.exgw.vdu.agent.ExgwVduDpAgent',
            '-DCLUSTER_ID=${env.CONSOLE_ID}',
            '-DDEFAULT_SIM_MODE=OFF',
            'tr.com.havelsan.cmscore.mw.dpagent.DPAgent'
          ]
          work_dir: '${env.CMS_ROOT}'

      - name: 'EXGW-SEP'
        instances: 2
        tags: ['dpagent','exgw']
        ttl: '15s'
        depends_on: []
        depends_min_passing: 0
        start:
          cmd: 'java.exe'
          args: [
            '-DAGENT_ID=EXGW-SEP',
            '-DAGENT_CLASS=tr.com.havelsan.agosta.c2is.exgw.sep.agent.ExgwSepDPAgent',
            '-DCLUSTER_ID=${env.CONSOLE_ID}',
            '-DDEFAULT_SIM_MODE=OFF',
            'tr.com.havelsan.cmscore.mw.dpagent.DPAgent'
          ]
          work_dir: '${env.CMS_ROOT}'

      - name: 'EXGW-AOM'
        instances: 2
        tags: ['dpagent','exgw']
        ttl: '15s'
        depends_on: []
        depends_min_passing: 0
        start:
          cmd: 'java.exe'
          args: [
            '-DAGENT_ID=EXGW-AOM',
            '-DAGENT_CLASS=tr.com.havelsan.agosta.c2is.exgw.aom.agent.ExgwAomDPAgent',
            '-DCLUSTER_ID=${env.CONSOLE_ID}',
            '-DDEFAULT_SIM_MODE=OFF',
            'tr.com.havelsan.cmscore.mw.dpagent.DPAgent'
          ]
          work_dir: '${env.CMS_ROOT}'

      - name: 'EXGW-WEA'
        instances: 2
        tags: ['dpagent','exgw']
        ttl: '15s'
        depends_on: []
        depends_min_passing: 0
        start:
          cmd: 'java.exe'
          args: [
            '-DAGENT_ID=EXGW-WEA',
            '-DAGENT_CLASS=tr.com.havelsan.agosta.c2is.exgw.wea.agent.ExgwWeaDPAgent',
            '-DCLUSTER_ID=${env.CONSOLE_ID}',
            '-DDEFAULT_SIM_MODE=OFF',
            'tr.com.havelsan.cmscore.mw.dpagent.DPAgent'
          ]
          work_dir: '${env.CMS_ROOT}'

      # - name: 'EXGW-TCM'
      #   instances: 2
      #   tags: ['dpagent','exgw']
      #   ttl: '15s'
      #   start:
      #     cmd: 'java.exe'
      #     args: [
      #       '-DAGENT_ID=EXGW-TCM',
      #       '-DAGENT_CLASS=tr.com.havelsan.agosta.c2is.exgw.tcm.agent.ExgwTcmDPAgent',
      #       '-DCLUSTER_ID=${env.CONSOLE_ID}',
      #       '-DDEFAULT_SIM_MODE=OFF',
      #       'tr.com.havelsan.cmscore.mw.dpagent.DPAgent'
      #     ]
      #     work_dir: '${env.CMS_ROOT}'

      - name: 'TMA-DP'
        instances: 2
        tags: ['dpagent','exgw']
        ttl: '15s'
        depends_on: []
        depends_min_passing: 0
        start:
          cmd: 'java.exe'
          args: [
            '-DAGENT_ID=TMA-DP',
            '-DAGENT_CLASS=tr.com.havelsan.agosta.c2is.tma.agent.TmaDpAgent',
            '-DCLUSTER_ID=${env.CONSOLE_ID}',
            '-DDEFAULT_SIM_MODE=OFF',
            'tr.com.havelsan.cmscore.mw.dpagent.DPAgent'
          ]
          work_dir: '${env.CMS_ROOT}'

  services_agent:
    enabled: true
    agent_id: '${env.NODE_NAME}'
    orders_prefix: 'orders/services'
    ack_prefix: 'acks/services'
    service_address: '${env.CSB_IP}'

